### ISSUE TITLE
安卓平台报错，是不是我漏了什么

### ISSUE THREAD

**Issue by huangzuizui** [reactnativecn/react-native-jpush#1]
安卓报错如下：
build file '/Users/sujiexu/Desktop/zuizuiApp/nodeTest/reactNative/TestApp18/android/app/build.gradle': 85: unexpected token: APP_CHANNEL @ line 85, column 13.
                 APP_CHANNEL: "developer-default"

**Comment by lvbingru** [comment]
哦，文档里面里面少了逗号
manifestPlaceholders = [
// 每一项之间需要逗号分隔
    JPush_APPID: "JPush的APPID",        //在此修改JPush的APPID
    APP_CHANNEL: "应用渠道号"      //应用渠道号
]
