### ISSUE TITLE
JPush_APPID  和   APP_CHANEL  的值

### ISSUE THREAD

**Issue by wxjie** [reactnativecn/react-native-jpush#10]
manifestPlaceholders = [
    JPush_APPID: "JPush的APPID",   //在此修改JPush的APPID
    APP_CHANNEL: "应用渠道号"      //应用渠道号
]
jpush appid  和 应用渠道号是什么，本人之前没用过后台推送

**Comment by tdzl2003** [comment]
APPID是在极光推送的官网上申请注册的。

APP_CHANNEL是你自己根据应用的发布渠道定义的名字。

详情参考极光推送官网。
