### ISSUE TITLE
极光推送自定义消息无法接收到

### ISSUE THREAD

**Issue by liuchungui** [reactnativecn/react-native-jpush#16]
推送通知能接收到，但是自定义消息无法接收到。

**Comment by liveKang** [comment]
你对自定义消息在代码里面做接受广播处理了吗？

**Comment by tdzl2003** [comment]
这个组件目前还不支持自定义消息。自定义消息需要自行编写一部分安卓原生代码，另外似乎自定义消息在iOS下不存在。

**Comment by jiexishede** [comment]
@tdzl2003  现在　ｉＯＳ能接受自定义消息了吗？？
