### ISSUE TITLE
结束掉后台无法收到消息

### ISSUE THREAD

**Issue by he5310** [reactnativecn/react-native-jpush#18]
结束掉应用后台无法收到推送(参考http://docs.jpush.io/guideline/faq/#android)。总感觉应该有解决办法的（因为其他原生安卓应用即使没有加入白名单杀掉后台一样可以接收到推送，如果一时找不到解决办法，就放弃jpush，用原生的推送了）。

**Comment by shiyigithub** [comment]
maybe you can add the app to auto-start list

**Comment by tdzl2003** [comment]
只能参考极光推送本身的文档进行送达率调优
