### ISSUE TITLE
请问极光上项目的AppKey配置在哪个地方

### ISSUE THREAD

**Issue by roveroc** [reactnativecn/react-native-jpush#2]
请问极光上项目的AppKey配置在哪个地方

**Comment by tdzl2003** [comment]
AppKey前端应该不会用到，不需要配置，是在用于发送推送的服务器方配置的。

将AppKey配置在前端是不安全的，一旦AppKey泄露，任何人都可以给你的用户发送推送通知了。

**Comment by ramy612** [comment]
APPKEY在前端是需要配置的，Master Secret是给服务端配置用的，没有appkey是不能够完成注册并获得clientid的……

**Comment by tdzl2003** [comment]
哦，好吧，貌似极光叫法不一样= =
