### ISSUE TITLE
ios下使用插件，报错：Unable to resolve module react-native-jpush from...

### ISSUE THREAD

**Issue by pampang** [reactnativecn/react-native-jpush#24]
https://github.com/facebook/react-native/issues/4968

错误类型与上面的网址所述一致，尝试过`rm -rf node_modules`然后重新安装，问题依然存在。

手机系统：ios,
开发环境：MBA，
RN版本：0.25.1

**Comment by tdzl2003** [comment]
是否安装模块后没重启packager……
