### ISSUE TITLE
我想做一个定时推送通知的功能

### ISSUE THREAD

**Issue by mvpdream** [reactnativecn/react-native-jpush#26]
rt 该怎么实现呢

**Comment by TinChak** [comment]
后端通过接口实现，客户端只负责调用接口而已。

**Comment by mvpdream** [comment]
那定时怎么搞？

**Comment by mvpdream** [comment]
定时是客户端定时去请求服务器调用  还是服务器定时发送数据到客户端呢

**Comment by tdzl2003** [comment]
不清楚极光推送有没有定时推送通知的功能，印象里好像没有，至少这个组件应该是没有这个功能。所以只能在服务器上定时调用极光推送的推送接口来实现。
