### ISSUE TITLE
安卓下运行找不到模块错误

### ISSUE THREAD

**Issue by liiklin** [reactnativecn/react-native-jpush#3]
文档中ios应该是引入libz.tbd

安卓下运行找不到模块错误`undefined is not an object (evaluating 'nativeModule.requestPermissions')`

**Comment by liiklin** [comment]
requestPermissions方法只在ios下有效。

**Comment by wxjie** [comment]
android 那应该怎么

**Comment by liiklin** [comment]
去看看jpush官方文档，安卓的sdk没这个方法。

**Comment by wxjie** [comment]
好的，谢谢，是我没有使用  rnpm link 指令。

2016-03-18 15:27 GMT+08:00 liiklin <notifications@github.com>:
