### ISSUE TITLE
关于react-native-jpush 配置完后没有反应

### ISSUE THREAD

**Issue by liz1113012618** [reactnativecn/react-native-jpush#33]
"dependencies": {
    "react-native": "^0.20.0",
    "react-native-jpush": "^1.0.8"
  }
上面是我的版本号，完全按上面配置后，请问我发送消息
![b2fd69c2-1927-48a3-80a2-cb6ddd3a801f](https://cloud.githubusercontent.com/assets/18205523/17240772/0cb08404-55a0-11e6-989c-75c867ebf099.png)
请问这是什么原因，难道按上面配置完后还不能发布消息么，或者客户端还需要单独在极光注册么？

**Comment by tdzl2003** [comment]
配置完要启动应用并将应用退到后台
