### ISSUE TITLE
android app 关闭后，无法推送？

### ISSUE THREAD

**Issue by gongchao** [reactnativecn/react-native-jpush#35]
react native 0.32

**Comment by dellheng** [comment]
android 推送不是操作系统级别的 关闭进程后就无法推送了，可以配置android:process参数将PushService放在其他进程中

**Comment by tdzl2003** [comment]
jPush已经自带了相应的配置，我们这里实际测试的时候，app关闭后是可以推送的。不过少部分安卓设备可能会有更严格的权限管理或后台运行策略，这种情况如何提高送达率请参考极光推送本身的文档。
