### ISSUE TITLE
jpush推送组件不能在后台运行正常接收通知

### ISSUE THREAD

**Issue by ramy612** [reactnativecn/react-native-jpush#9]
在小米手机上做测试的时候发现如果关闭了应用之后就不能收到消息通知了？
这是不是一个bug啊，记得原先开发原生的时候是可以收到的啊……求解答或解决方案

**Comment by tdzl2003** [comment]
是不是系统的安全中心控制了应用权限？小米系统貌似为了运行流畅，会限制应用在后台运行。

**Comment by ramy612** [comment]
@tdzl2003 
确实是小米应用自启动管理的问题，在小米手机中找到“安全中心”-》“授权管理”-》“自启动管理”中设置自己的应用自启动即可！问题解决，谢谢 @tdzl2003
